---
# ByteFreezer Packer Role

- name: Create packer directories
  file:
    path: "{{ bytefreezer_config_dir }}/packer"
    state: directory
    mode: '0755'

- name: Deploy packer configuration
  template:
    src: config.yaml.j2
    dest: "{{ bytefreezer_config_dir }}/packer/config.yaml"
    mode: '0600'
  notify: restart packer

- name: Deploy packer systemd service
  template:
    src: packer.service.j2
    dest: /etc/systemd/system/bytefreezer-packer.service
    mode: '0644'
  notify:
    - reload systemd
    - restart packer

- name: Pull packer image
  docker_image:
    name: "{{ image_registry }}/bytefreezer-packer:{{ image_tag }}"
    source: pull
    force_source: yes

- name: Start packer service
  systemd:
    name: bytefreezer-packer
    state: started
    enabled: yes
    daemon_reload: yes
