{{- if not .Values.s3.existingSecret }}
{{- $accessKey := include "bytefreezer.s3AccessKey" . }}
{{- $secretKey := include "bytefreezer.s3SecretKey" . }}
{{- if or $accessKey $secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytefreezer.s3SecretName" . }}
  labels:
    {{- include "bytefreezer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $accessKey }}
  accessKey: {{ $accessKey | b64enc | quote }}
  {{- end }}
  {{- if $secretKey }}
  secretKey: {{ $secretKey | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if not .Values.controlService.existingSecret }}
{{- if .Values.controlService.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytefreezer.controlSecretName" . }}
  labels:
    {{- include "bytefreezer.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.controlService.apiKey | b64enc | quote }}
{{- end }}
{{- end }}
