{{- if and .Values.controlService.apiKey (not .Values.controlService.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" . }}-control
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ .Values.controlService.apiKey | b64enc | quote }}
{{- end }}
